// html.h
#define _HTML_h

#ifndef _HTML_h
#define _HTML_h

#if defined(ARDUINO) && ARDUINO >= 100
	#include "arduino.h"
#else
	#include "WProgram.h"
#endif

const char html_popup[] PROGMEM = {
	"<!-- The Modal -->"
	"<div id=\"modalPopup\" class=\"modal\">"
	"    <!-- Modal content -->"
	"    <div class=\"modal-content\">"
	"        <span class=\"close\">&times;</span>"
	"        <div id=\"modalText\">Some text in the Modal..</div>"
	"        <input type=\"button\" id=\"okButton\" value=\"Ok\">"
	"        <input type=\"button\" id=\"cancelButton\" value=\"Annulla\">"
	"    </div>"
	"</div>  "

};

const char html_index[] PROGMEM = {
	"<!--copiare da qui-->"
	"<h1 id=\"head\">Webduino</h1>"
	"<ul id=\"navigation\">"
	"    <li><span class=\"active\">Home</span></li>"
	"    <li><a href=\"settings.html\" class=\"button hvr-underline-from-center\">Impostazioni</a></li>"
	"    <li><a href=\"heater.html\" class=\"button hvr-underline-from-center\">Riscaldamento</a></li>"
	"</ul>"
	"<!--Content--->"
	"<div id=\"content\" class=\"container_16 clearfix\">"
	"    <div class=\"grid_5\">"
	""
	"        <input type=\"button\" id=\"popupButton\" value=\"popup\">"
	""
	"        <div class=\"box\">"
	""
	"            <h2>Stato scheda</h2>"
	"            <p>"
	"                <strong>Date e ora : </strong> 01-01-1970 00:01:09 <br>"
	"                <strong>IP Address : </strong> 192.168.1.9<br>"
	"                <strong>MAC Address : </strong> 18:fe:34:d4:c6:87 <br>"
	"                <strong>ID scheda: </strong> 0 <br>"
	""
	"            </p>"
	"        </div>"
	""
	"        <div class=\"box\">"
	""
	"            <h2>Comandi</h2>"
	""
	"            <label id=\"summary\">summary</label><br>"
	"            <label id=\"command\">command</label><br>"
	"            <label id=\"timer\">timer</label>"
	""
	"                <p>"
	"                    <strong>Power : </strong><label class=\"input-toggle\"><input type=\"checkbox\" id=\"powerCheckBox\"><span></span></label><br><br>"
	"                    <strong>Reset : </strong><input type=\"button\" id=\"resetButton\" value=\"reset\"><span></span></label>"
	"                    <br><br>"
	"                    <strong>Shield : </strong><label class=\"input-toggle\"><input type=\"button\""
	"                                                                                 id=\"shieldButton\"><span></span></label><br><br>"
	""
	""
	"                    <input type='hidden' name='command' value='manual'>"
	""
	"                </p>"
	""
	""
	""
	"        </div>"
	""
	""
	"    </div>"
	"</div>"
	"<!--Footer --->"
	"<div id=\"foot\">"
	"    <div class=\"container_16 clearfix\">"
	"        <div class=\"grid_16\"><a href=\"#\">Contact Me</a></div>"
	"    </div>"
	"</div>"
	"</body>"
	"</html>"
	""

};

const char html_settings[] PROGMEM = {
	
	"<!--copiare da qui-->"
	"<h1 id=\"head\">Webduino</h1>"
	"<ul id=\"navigation\">"
	"    <li><a href=\"index.html\" class=\"button hvr-underline-from-center\">Home</a></li>"
	"    <li><span class=\"active\">Impostazioni</span></li>"
	"    <li><a href=\"heater.html\" class=\"button hvr-underline-from-center\">Riscaldamento</a></li>"
	"</ul>"
	"<!--Content--->"
	"<div id=\"content\" class=\"container_16 clearfix\">"
	"    <div class=\"grid_5\">"
	"        <div class=\"box\">"
	""
	"            <h2>Impostazioni scheda</h2>"
	""
	"            <label id=\"summary\">summary</label><br>"
	"            <label id=\"command\">command</label><br>"
	"            <label id=\"timer\">timer</label>"
	""
	"            <form action='/command' method='POST' id='shield'>"
	"                <p>"
	"                    <strong>Local Port: </strong><input type='number' id='localport' name='localport' value='80' step='1' min='1' max='9999'><BR><BR>"
	"                    <strong>Shield name: </strong><input type='text'  id='shieldname' name='shieldname' value='shieldname' size='29' maxlength='29'><BR><BR>"
	"                    <strong>SSID: </strong><input type='text' id='ssid' name='ssid' value='SSID' size='32' maxlength='32'><BR><BR>"
	"                    <strong>password: </strong><input type='text' id='password' name='password' value='password' size='96' maxlength='96'><BR><BR>"
	"                    <strong>Server name: </strong><input type='text' id='servername' name='servername' value='Server name' size='29' maxlength='29'><BR><BR>"
	"                    <strong>Server Port: </strong><input type='number' id='serverport' name='serverport' value='8080' step='1' min='1' max='9999'><BR><BR>"
	""
	"                    <input type='hidden' name='command' value='shieldsettings'>"
	"                    <input type='submit' value=\"save\" onclick='whichPressed=this'>"
	"                </p>"
	"            </form>"
	"        </div>"
	""
	"    </div>"
	"</div>"
	"<!--Footer --->"
	"<div id=\"foot\">"
	"    <div class=\"container_16 clearfix\">"
	"        <div class=\"grid_16\"><a href=\"#\">Contact Me</a></div>"
	"    </div>"
	"</div>"
	"</body>"
	"</html>"
	""

};

const char html_heater[] PROGMEM = {

	"<!--copiare da qui-->"
	"<h1 id=\"head\">Webduino</h1>"
	"<ul id=\"navigation\">"
	"    <li><a href=\"index.html\" class=\"button hvr-underline-from-center\">Home</a></li>"
	"    <li><a href=\"settings.html\" class=\"button hvr-underline-from-center\">Impostazioni</a></li>"
	"    <li><span class=\"active\">Riscaldamento</span></li>"
	"</ul>"
	"<!--Content--->"
	"<div id=\"content\" class=\"container_16 clearfix\">"
	"    <div class=\"grid_5\">"
	"        <div class=\"box\">"
	""
	"            <h2>Riscaldamento</h2>"
	"            <form action='/command' method='POST' id='heater'>"
	"                <p>"
	"                    <strong>Abilitato : </strong><label class=\"input-toggle\"><input type=\"checkbox\" id=\"heaterEnabled\""
	"                                                                                    name=\"enabled\"><span></span></label><br>"
	"                    <strong>Pin rele : </strong><label id=\"pinSelectValue\" hidden>audi</label>"
	"                    <select id=\"pinSelect\" name=\"pin\">"
	"                        <option value=\"D1\">D1</option>"
	"                        <option value=\"D2\">D2</option>"
	"                        <option value=\"D3\">D3</option>"
	"                        <option value=\"D4\">D4</option>"
	"                        <option value=\"D5\">D5</option>"
	"                    </select>"
	"                    <br><br>"
	"                    <input type='hidden' name='command' value='heatersettings'>"
	"                    <input type='submit' value=\"save\">"
	"                </p>"
	"            </form>"
	"        </div>"
	""
	"        <div class=\"box\">"
	""
	"            <h2>Riscaldamento</h2>"
	""
	"            <label id=\"summary\">summary</label><br>"
	"            <label id=\"command\">command</label><br>"
	"            <label id=\"timer\">timer</label>"
	""
	"            <form action='/command' method='POST' id='startManualForm'>"
	"                <p>"
	"                    Minutesy:<input type='number' name='duration' value='30' min=\"1\" max=\"30\"><BR>"
	"                    Target:<input type='number' name='target' value='22.0' step='0.10'><BR>"
	"                    Sensor:<input type='radio' name='sensor' value='0' checked>Local<input type='radio' name='sensor'"
	"                                                                                           value='1'>Remote<BR>"
	"                    <input type='hidden' name='command' value='manual'>"
	"                    <input type='submit' value='start manual'>"
	"                </p>"
	"            </form>"
	""
	"            <form action='/command' method='POST' id='manualOffForm'>"
	"                <p>"
	"                    Minutesx:<input type='number' name='duration' value='30' min=\"1\" max=\"30\"><BR>"
	"                    <input type='hidden' name='command' value='manualoff'>"
	"                    <input type='submit' value='start manual off'>"
	"                </p>"
	"            </form>"
	""
	""
	"            <div id='manual'>"
	"                <form action='/command' method='POST' id='stopManualForm'>"
	"                    <p>"
	"                        <input type='hidden' name='command' value='manualend'>"
	"                        <input type='submit' value='stop manual'>"
	"                    </p>"
	"                </form>"
	"            </div>"
	""
	"        </div>"
	""
	""
	"    </div>"
	"</div>"
	"<!--Footer --->"
	"<div id=\"foot\">"
	"    <div class=\"container_16 clearfix\">"
	"        <div class=\"grid_16\"><a href=\"#\">Contact Me</a></div>"
	"    </div>"
	"</div>"
	"</body>"
	"</html>"
	""


};

#endif

