// js.h

#define _JS_h

#ifndef _JS_h
#define _JS_h

#if defined(ARDUINO) && ARDUINO >= 100
	#include "arduino.h"
#else
	#include "WProgram.h"
#endif

/* ricordarsi di cambiarre il path!!!!!!*/
const char js_webduino[] PROGMEM = {
	"var serverPath = '';"
	"var heaterStatusPath = serverPath + '/heaterstatus';"
	"var commandPath = serverPath + '/command';"
	"var settingsPath = serverPath + '/settings';"
	""
	""
	""
	"var popFunction = function pop(modalText,okCallback,cancelCallback) {"
	""
	"    document.getElementById('modalPopup').style.display = 'block';"
	""
	"    document.getElementById('modalText').innerHTML = modalText;"
	""
	"    var okButton = document.getElementById('okButton');"
	"    var cancelButton = document.getElementById('cancelButton');"
	"    if (okCallback != null) {"
	"        document.getElementById('okButton').style.display = 'block';"
	"        document.getElementById('okButton').onclick = okCallback;"
	"    } else {"
	"        document.getElementById('okButton').style.display = 'none'"
	"    }"
	""
	"    var span = document.getElementsByClassName(\"close\")[0];"
	"    if (cancelCallback != null) {"
	"        document.getElementById('cancelButton').style.display = 'block';"
	"        document.getElementById('cancelButton').onclick = cancelCallback;"
	""
	"        /* When the user clicks on <span> (x), close the modal*/"
	"        span.style.display = 'block';"
	"        span.onclick = function() {"
	"            hideFunction();"
	"        }"
	""
	"        /* When the user clicks anywhere outside of the modal, close it*/"
	"        window.onclick = function(event) {"
	"            if (event.target == modal) {"
	"                hideFunction();"
	"            }"
	"        }"
	""
	"    } else {"
	"        span.style.display = 'none';"
	"        document.getElementById('cancelButton').style.display = 'none'"
	"    }"
	"};"
	""
	"var hideFunction = function hide() {"
	"    document.getElementById('modalPopup').style.display = 'none';"
	"};"
	""
	"/*To detect escape button*/"
	"document.onkeydown = function(evt) {"
	"    evt = evt || window.event;"
	"    if (evt.keyCode == 27) {"
	"        hideFunction('popDiv');"
	"    }"
	"};"
	""
	"function getJson(path, callback) {"
	"    popFunction('Aggiornamento...' /*,function () {"
	"     alert('ok');"
	"     }*/);"
	"    var request = new XMLHttpRequest();"
	"    request.open('GET', path, true);"
	"    request.setRequestHeader(\"X-Requested-With\", \"XMLHttpRequest\");"
	"    request.onload = function () {"
	"        if (this.status >= 200 && this.status < 400) {"
	"            var json = JSON.parse(this.response);"
	"            callback(json);"
	"        } else {"
	"            alert('errore:'+this.status);"
	""
	"        }"
	"        hideFunction();"
	"    };"
	"    request.send();"
	"}"
	""
	"function formInputToJSON(form) {"
	"    var data = {};"
	"    for (var i = 0, ii = form.length; i < ii; ++i) {"
	"        var input = form[i];"
	"        if (input.name) {"
	""
	"            if (input.type == 'number') {"
	"                data[input.name] = Number(input.value);"
	"            }"
	"            else if (input.type == 'radio' && input.checked) {"
	"                if (input.value == '0')"
	"                    data[input.name] = false;"
	"                else"
	"                    data[input.name] = true;"
	"            }"
	"            else if (input.type == 'checkbox') {"
	"                if (input.checked)"
	"                    data[input.name] = true;"
	"                else"
	"                    data[input.name] = false;"
	"            }"
	"            else {"
	"                data[input.name] = input.value;"
	"            }"
	"        }"
	"    }"
	"    return data;"
	"}"
	""
	"function sendCommand(data, callback) {"
	""
	"    var xhr = new XMLHttpRequest();"
	"    xhr.open('POST', commandPath, true);"
	"    xhr.setRequestHeader('Content-Type', 'application/json; charset=UTF-8');"
	"    xhr.send(JSON.stringify(data));"
	"    document.getElementById('command').innerHTML = 'command sent' + JSON.stringify(data);"
	"    xhr.onloadend = function () {"
	"        hideFunction();"
	"        result = xhr.responseText;"
	"        var json = JSON.parse(result);"
	"        callback(json);"
	"    };"
	"    popFunction('Invio comando in corso...' /*,function () {"
	"        alert('ok');"
	"    }*/);"
	"}"
	""

};

const char js_settings[] PROGMEM = {
	""
	"function load() {"
	""
	"    document.getElementById('shield').onsubmit = function (event) {"
	"        event.preventDefault();"
	"        sendPost(this, commandResponse);"
	"    };"
	"    getJson(settingsPath, refreshFunction);"
	"}"
	""
	"function commandResponse(json) {"
	"    document.getElementById('command').innerHTML += 'command result' + JSON.stringify(json);"
	"    getJson(settingsPath, refreshFunction);"
	"}"
	""
	"var refreshFunction = function refresh(json) {"
	"    document.getElementById('summary').innerHTML = JSON.stringify(json);"
	""
	"    document.getElementById('localport').value = json.localport;"
	"    document.getElementById('shieldname').value = json.shieldname;"
	"    document.getElementById('ssid').value = json.ssid;"
	"    document.getElementById('password').value = json.password;"
	"    document.getElementById('servername').value = json.servername;"
	"    document.getElementById('serverport').value = json.serverport;"
	"};"
	""
	"function sendPost(form, callback) {"
	"    var data = formInputToJSON(form);"
	"    sendCommand(data, callback);"
	"}"
	""

};

const char js_heater[] PROGMEM = {
	"var startManualForm;"
	"var manualOffForm;"
	"var stopManualForm;"
	"var counter = 0;"
	""
	"function load() {"
	""
	"    document.getElementById('heater').onsubmit = function (event) {"
	"        event.preventDefault();"
	"        sendPost(this, commandResponse);"
	"    };"
	"    startManualForm = document.getElementById('startManualForm');"
	"    startManualForm.onsubmit = function () {"
	"        event.preventDefault();"
	"        sendPost(this, commandResponse);"
	"    };"
	"    manualOffForm = document.getElementById('manualOffForm');"
	"    manualOffForm.onsubmit = function () {"
	"        event.preventDefault();"
	"        sendPost(this, commandResponse);"
	"    };"
	"    stopManualForm = document.getElementById('stopManualForm');"
	"    stopManualForm.onsubmit = function () {"
	"        event.preventDefault();"
	"        sendPost(this, commandResponse);"
	"    };"
	"    startManualForm.style.display = 'none';"
	"    manualOffForm.style.display = 'none';"
	"    stopManualForm.style.display = 'none';"
	""
	"    getJson(heaterStatusPath, refreshFunction);"
	""
	"    setInterval(function(){"
	"        document.getElementById('timer').innerHTML = counter++;"
	"        if (counter % 20 == 0)"
	"            getJson(heaterStatusPath, refreshFunction); }, 1000);"
	"}"
	""
	"function commandResponse(json) {"
	"    document.getElementById('command').innerHTML += 'command result' + JSON.stringify(json);"
	"    getJson(heaterStatusPath, refreshFunction);"
	"}"
	""
	"var refreshFunction = function refresh(json) {"
	"    document.getElementById('summary').innerHTML = JSON.stringify(json);"
	""
	"    if (json.enabled)"
	"        document.getElementById('heaterEnabled').checked = true;"
	"    else"
	"        document.getElementById('heaterEnabled').checked = false;"
	""
	"    var pinSelectControl = document.getElementById('pinSelect');"
	"    for (var i, j = 0; i = pinSelectControl.options[j]; j++) {"
	"        if (i.value == json.pin) {"
	"            pinSelectControl.selectedIndex = j;"
	"            break;"
	"        }"
	"    }"
	"    if (json.status == 'manual' || json.status == 'manualoff') {"
	"        startManualForm.style.display = 'none';"
	"        manualOffForm.style.display = 'none';"
	"        stopManualForm.style.display = 'block';"
	""
	"    } else {"
	"        startManualForm.style.display = 'block';"
	"        manualOffForm.style.display = 'block';"
	"        stopManualForm.style.display = 'none';"
	"    }"
	"};"
	""
	"function sendPost(form, callback) {"
	"    startManualForm.style.display = 'block';"
	"    manualOffForm.style.display = 'block';"
	"    stopManualForm.style.display = 'block';"
	"    var data = formInputToJSON(form);"
	"    sendCommand(data, callback);"
	"}"
	""



};

const char js_index[] PROGMEM = {
	"function load() {"
	""
	"    var powerCheckBox = document.getElementById('powerCheckBox').onclick = onClickPowerCheckBoxFunction;"
	"    getJson(settingsPath, refreshFunction);"
	""
	"    document.getElementById('popupButton').onclick = provaFunction;"
	""
	"}"
	""
	"var provaFunction = function prova() {"
	""
	"    popFunction(\"prova\",function () {"
	"        alert('ok');"
	"    },null/*function () {"
	"        alert('cancel');"
	"    }*/)"
	"}"
	""
	"var refreshFunction = function refresh(json) {"
	"    document.getElementById('summary').innerHTML = JSON.stringify(json);"
	"    if (json.hasOwnProperty(\"power\")) {"
	"        if (json.power == \"on\")"
	"            document.getElementById('powerCheckBox').checked = true;"
	"        else"
	"            document.getElementById('powerCheckBox').checked = false;"
	"    }"
	"};"
	""
	"function sendPost(form, callback) {"
	"    var data = formInputToJSON(form);"
	"    sendCommand(data, callback);"
	"}"
	""
	"var onClickPowerCheckBoxFunction = function onClickPowerCheckBox() {"
	""
	"    var jsonString;"
	"    if ( this.checked == true ) {"
	"        alert( \"Accendere il dispositivo?\" );"
	"        jsonString = '{\"command\" : \"power\", \"status\" : \"on\"}';"
	"    } else {"
	"        alert( \"Spengere il dispositivo?\" );"
	"        var jsonString = '{\"command\" : \"power\", \"status\" : \"off\"}';"
	"    }"
	""
	"    var json =  JSON.parse(jsonString);"
	"    sendCommand(json, refreshFunction);"
	""
	"}"
	""

};

#endif

