// js.h

#ifndef _JS_h
#define _JS_h

#if defined(ARDUINO) && ARDUINO >= 100
	#include "arduino.h"
#else
	#include "WProgram.h"
#endif

/* ricordarsi di cambiarre il path!!!!!!*/
const char js_webduino[] PROGMEM = {
	"var serverPath = '';"
	"var heaterStatusPath = serverPath + '/heaterstatus';"
	"var commandPath = serverPath + '/command';"
	""
	"function getJson(path, callback) {"
	"    var request = new XMLHttpRequest();"
	"    request.open('GET', path, true);"
	"    request.setRequestHeader(\"X-Requested-With\", \"XMLHttpRequest\");"
	"    request.onload = function () {"
	"        if (this.status >= 200 && this.status < 400) {"
	"            var json = JSON.parse(this.response);"
	"            callback(json);"
	"        }"
	"    };"
	"    request.send();"
	"}"
	""
	"function formInputToJSON(form) {"
	"    var data = {};"
	"    for (var i = 0, ii = form.length; i < ii; ++i) {"
	"        var input = form[i];"
	"        if (input.name) {"
	""
	"            if (input.type == 'number') {"
	"                data[input.name] = Number(input.value);"
	"            }"
	"            else if (input.type == 'radio' && input.checked) {"
	"                if (input.value == '0')"
	"                    data[input.name] = false;"
	"                else"
	"                    data[input.name] = true;"
	"            }"
	"            else if (input.type == 'checkbox') {"
	"                if (input.checked)"
	"                    data[input.name] = true;"
	"                else"
	"                    data[input.name] = false;"
	"            }"
	"            else {"
	"                data[input.name] = input.value;"
	"            }"
	"        }"
	"    }"
	"    return data;"
	"}"
	""
	"function sendCommand(data, callback) {"
	"    var xhr = new XMLHttpRequest();"
	"    xhr.open('POST', commandPath, true);"
	"    xhr.setRequestHeader('Content-Type', 'application/json; charset=UTF-8');"
	"    xhr.send(JSON.stringify(data));"
	"    document.getElementById('command').innerHTML = 'command sent' + JSON.stringify(data);"
	"    xhr.onloadend = function () {"
	"        result = xhr.responseText;"
	"        var json = JSON.parse(result);"
	"        callback(json);"
	"    };"
	"}"
	""

};

const char js_heater[] PROGMEM = {
	"var whichPressed;"
	"var startManualForm;"
	"var manualOffForm;"
	"var stopManualForm;"
	"var counter = 0;"
	""
	"function load() {"
	""
	"    document.getElementById('heater').onsubmit = function (event) {"
	"        event.preventDefault();"
	"        sendPost(this, commandResponse);"
	"    };"
	"    startManualForm = document.getElementById('startManualForm');"
	"    startManualForm.onsubmit = function () {"
	"        event.preventDefault();"
	"        sendPost(this, commandResponse);"
	"    };"
	"    manualOffForm = document.getElementById('manualOffForm');"
	"    manualOffForm.onsubmit = function () {"
	"        event.preventDefault();"
	"        sendPost(this, commandResponse);"
	"    };"
	"    stopManualForm = document.getElementById('stopManualForm');"
	"    stopManualForm.onsubmit = function () {"
	"        event.preventDefault();"
	"        sendPost(this, commandResponse);"
	"    };"
	"    startManualForm.style.display = 'none';"
	"    manualOffForm.style.display = 'none';"
	"    stopManualForm.style.display = 'none';"
	""
	"    getJson(heaterStatusPath, refreshFunction);"
	""
	"    setInterval(function(){"
	"        document.getElementById('timer').innerHTML = counter++;"
	"        if (counter % 20 == 0)"
	"            getJson(heaterStatusPath, refreshFunction); }, 1000);"
	"}"
	""
	"function commandResponse(json) {"
	"    /*whichPressed.style.visibility = \"visible\";*/"
	"    document.getElementById('command').innerHTML += 'command result' + JSON.stringify(json);"
	"    getJson(heaterStatusPath, refreshFunction);"
	"}"
	""
	"var refreshFunction = function refresh(json) {"
	"    document.getElementById('summary').innerHTML = JSON.stringify(json);"
	""
	"    if (json.enabled)"
	"        document.getElementById('heaterEnabled').checked = true;"
	"    else"
	"        document.getElementById('heaterEnabled').checked = false;"
	""
	"    var pinSelectControl = document.getElementById('pinSelect');"
	"    for (var i, j = 0; i = pinSelectControl.options[j]; j++) {"
	"        if (i.value == json.pin) {"
	"            pinSelectControl.selectedIndex = j;"
	"            break;"
	"        }"
	"    }"
	"    if (json.status == 'manual' || json.status == 'manualoff') {"
	"        startManualForm.style.display = 'none';"
	"        manualOffForm.style.display = 'none';"
	"        stopManualForm.style.display = 'block';"
	""
	"    } else {"
	"        startManualForm.style.display = 'block';"
	"        manualOffForm.style.display = 'block';"
	"        stopManualForm.style.display = 'none';"
	"    }"
	"    whichPressed.style.visibility = \"visible\";"
	"};"
	""
	"function sendPost(form, callback) {"
	"    /*whichPressed.style.visibility = \"hidden\";*/"
	"    startManualForm.style.display = 'block';"
	"    manualOffForm.style.display = 'block';"
	"    stopManualForm.style.display = 'block';"
	"    var data = formInputToJSON(form);"
	""
	"    sendCommand(data, callback);"
	"}"
	""


};

#endif

